name: Deployment workflow
on: 
    push:
        branches:

            - master

jobs:
    preparation:
        runs-on: ubuntu-latest
        steps:
            - name: preparation
              run: echo "preparing to display"
            - name: checks out the repository
              uses: actions/checkout@v4
            - name: "logs into Docker Hub"
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }} 
            -  name: "Build our code"
               env:
                  IMAGE_NAME: ci
                  VERSION: latest
                  USERNAME: mutiuadeniyi290
               run: |
                    docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
                    docker push $USERNAME/$IMAGE_NAME:$VERSION    